apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-app
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/vcluster-repo.git
    targetRevision: HEAD
    path: clusters/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
