apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
        revision: main
        directories:
          - path: clusters/dev/*
  template:
    metadata:
      name: '{{path.basename}}-vcluster'
    spec:
      project: default
      source:
        repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
