name: Port vCluster Deployment
on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster name'
        required: true
      namespace:
        description: 'Target namespace'
        default: 'vcluster-ns'

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Create vCluster manifest
        run: |
          cat <<EOF > clusters/dev/vcluster.yaml
          apiVersion: cluster.x-k8s.io/v1beta1
          kind: Cluster
          metadata:
            name: ${{ github.event.inputs.clusterName }}
          spec:
            infrastructureRef:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
              kind: VCluster
              name: ${{ github.event.inputs.clusterName }}
          EOF
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Deploy vCluster ${{ github.event.inputs.clusterName }}"
          branch: main
